windowrule {
    # Ignore maximize requests from all apps
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    # Fix XWayland drag issues on empty class/title windows
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

windowrule {
    name = vesktop-transparency
    match:class = ^(vesktop)$
    opacity = 0.90 0.80
}

windowrule {
    name = thunar-transparency
    match:class = ^(thunar)$
    opacity = 0.8 0.8
}

windowrule {
    name = firefox-transparency
    match:class = ^(firefox)$
    opacity = 0.95 0.95
}

windowrule {
    name = vscode-transparency
    match:class = ^(code)$
    opacity = 0.9 0.9
}

windowrule {
    name = obsidian-transparency
    match:class = ^(obsidian)$
    opacity = 0.90 0.9
}

windowrule {
    name = matrix-no-blur
    match:title = ^(cmatrix)$
    no_blur = true
}
